# Generated by Django 5.0.2 on 2024-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('password', models.CharField(default='default_password', max_length=100)),
            ],
        ),
    ]
