# Generated by Django 5.0.2 on 2024-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_customuseradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
