# Generated by Django 5.0.2 on 2024-04-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_poll_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='expiration_date',
            new_name='end_date',
        ),
    ]
