# Generated by Django 5.0.2 on 2024-04-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_expiration_date_poll_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
    ]
