# Generated by Django 5.0.2 on 2024-04-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_poll_expiration_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='expiration_datetime',
        ),
    ]
