# Generated by Django 5.0.2 on 2024-04-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_poll_expiration_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expiration_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
