# Generated by Django 5.0.2 on 2024-04-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_poll_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='expiration_date',
        ),
    ]
