# Generated by Django 5.0.6 on 2024-05-18 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_poll_end_date_poll_start_date_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloptions',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 6, 8, 7, 827811, tzinfo=datetime.timezone.utc)),
        ),
    ]
