# Generated by Django 5.0.6 on 2024-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_polloptions_votes_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
