# Generated by Django 5.0.6 on 2024-05-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_poll_end_date_alter_poll_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='polloptions',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
